{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "笔者目前遇到一个问题，当开启两个ipython进程的时候会遇到下列错误"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "```shell\n",
    "Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@13015ec0, see the next exception for details.\n",
    "org.datanucleus.exceptions.NucleusDataStoreException: Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@13015ec0, see the next exception for details.\n",
    "at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:516)\n",
    "at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:298)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n",
    "at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n",
    "at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n",
    "at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:631)\n",
    "at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:301)\n",
    "at org.datanucleus.NucleusContext.createStoreManagerForProperties(NucleusContext.java:1187)\n",
    "at org.datanucleus.NucleusContext.initialise(NucleusContext.java:356)\n",
    "at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:775)\n",
    "at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:333)\n",
    "at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:202)\n",
    "at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n",
    "at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n",
    "at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n",
    "at java.lang.reflect.Method.invoke(Method.java:606)\n",
    "at javax.jdo.JDOHelper$16.run(JDOHelper.java:1965)\n",
    "at java.security.AccessController.doPrivileged(Native Method)\n",
    "at javax.jdo.JDOHelper.invoke(JDOHelper.java:1960)\n",
    "at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1166)\n",
    "at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:808)\n",
    "at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:701)\n",
    "at org.apache.hadoop.hive.metastore.ObjectStore.getPMF(ObjectStore.java:365)\n",
    "at org.apache.hadoop.hive.metastore.ObjectStore.getPersistenceManager(ObjectStore.java:394)\n",
    "at org.apache.hadoop.hive.metastore.ObjectStore.initialize(ObjectStore.java:291)\n",
    "at org.apache.hadoop.hive.metastore.ObjectStore.setConf(ObjectStore.java:258)\n",
    "at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:73)\n",
    "at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)\n",
    "at org.apache.hadoop.hive.metastore.RawStoreProxy.<init>(RawStoreProxy.java:57)\n",
    "at org.apache.hadoop.hive.metastore.RawStoreProxy.getProxy(RawStoreProxy.java:66)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.newRawStore(HiveMetaStore.java:593)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:571)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:620)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:461)\n",
    "at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:66)\n",
    "at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:72)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:5762)\n",
    "at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:199)\n",
    "at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:74)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n",
    "at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n",
    "at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n",
    "at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1521)\n",
    "at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)\n",
    "at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)\n",
    "at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)\n",
    "at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)\n",
    "at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)\n",
    "at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1234)\n",
    "at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:174)\n",
    "at org.apache.hadoop.hive.ql.metadata.Hive.<clinit>(Hive.java:166)\n",
    "at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:503)\n",
    "at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:171)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n",
    "at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n",
    "at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n",
    "at org.apache.spark.sql.hive.client.IsolatedClientLoader.liftedTree1$1(IsolatedClientLoader.scala:183)\n",
    "at org.apache.spark.sql.hive.client.IsolatedClientLoader.<init>(IsolatedClientLoader.scala:179)\n",
    "at org.apache.spark.sql.hive.HiveContext.metadataHive$lzycompute(HiveContext.scala:227)\n",
    "at org.apache.spark.sql.hive.HiveContext.metadataHive(HiveContext.scala:186)\n",
    "at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:393)\n",
    "at org.apache.spark.sql.hive.HiveContext.defaultOverrides(HiveContext.scala:175)\n",
    "at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:178)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n",
    "at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)\n",
    "at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n",
    "at java.lang.reflect.Constructor.newInstance(Constructor.java:526)\n",
    "at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:234)\n",
    "at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)\n",
    "at py4j.Gateway.invoke(Gateway.java:214)\n",
    "at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:79)\n",
    "at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:68)\n",
    "at py4j.GatewayConnection.run(GatewayConnection.java:207)\n",
    "at java.lang.Thread.run(Thread.java:745)\n",
    "Caused by: java.sql.SQLException: Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@13015ec0, see the next exception for details.\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)\n",
    "at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)\n",
    "at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)\n",
    "at org.apache.derby.jdbc.Driver20.connect(Unknown Source)\n",
    "at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)\n",
    "at java.sql.DriverManager.getConnection(DriverManager.java:571)\n",
    "at java.sql.DriverManager.getConnection(DriverManager.java:187)\n",
    "at org.apache.commons.dbcp.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:78)\n",
    "at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)\n",
    "at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)\n",
    "at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)\n",
    "at org.datanucleus.store.rdbms.ConnectionFactoryImpl$ManagedConnectionImpl.getConnection(ConnectionFactoryImpl.java:501)\n",
    "... 76 more\n",
    "Caused by: java.sql.SQLException: Failed to start database 'metastore_db' with class loader org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1@13015ec0, see the next exception for details.\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)\n",
    "... 93 more\n",
    "Caused by: java.sql.SQLException: Another instance of Derby may have already booted the database /home/dmytro/work/shared_store/integration/metastore_db.\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)\n",
    "at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)\n",
    "... 90 more\n",
    "Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database /home/dmytro/work/shared_store/integration/metastore_db.\n",
    "at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\n",
    "at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.privGetJBMSLockOnDB(Unknown Source)\n",
    "at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.run(Unknown Source)\n",
    "at java.security.AccessController.doPrivileged(Native Method)\n",
    "at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.getJBMSLockOnDB(Unknown Source)\n",
    "at org.apache.derby.impl.store.raw.data.BaseDataFileFactory.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)\n",
    "at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)\n",
    "at org.apache.derby.impl.store.raw.RawStore.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)\n",
    "at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)\n",
    "at org.apache.derby.impl.store.access.RAMAccessManager.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.startModule(Unknown Source)\n",
    "at org.apache.derby.iapi.services.monitor.Monitor.bootServiceModule(Unknown Source)\n",
    "at org.apache.derby.impl.db.BasicDatabase.bootStore(Unknown Source)\n",
    "at org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.startProviderService(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(Unknown Source)\n",
    "at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(Unknown Source)\n",
    "at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Unknown Source)\n",
    "... 90 more\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "很显然，提示'metastore_db'冲突。\n",
    "解决方法：\n",
    "\n",
    "1.消除'metastore_db'锁死问题\n",
    "\n",
    "2.不同进程指向不同的'metastore_db'路径"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a href=\"https://issues.apache.org/jira/browse/SPARK-10872\">这里</a>是方法一:\n",
    "```shell\n",
    "删除文件夹metastore_db中的dbex.lck文件即可\n",
    "```\n",
    "\n",
    "对于方法二，目前还没有找到解决途径，2.0.0以后的spark版本已经启用了hive-site.xml设置。"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
